config/routes.rb
Rails.application.routes.draw do
  resources :versions
  resources :versions
  root 'versions#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'admin/signin' => 'admin#admin_signin'
  resources :photos
  resources :rooms
  get 'rooms/report/:id' => 'versions#report' , :as => 'report'
  post 'report/:id' => 'versions#creport' , :as => 'report_create'
  get 'admin/users' => 'admin#user' , :as => 'users'
  get 'admin/user/ban/:id' => 'admin#user_ban'
  get 'admin/user/ban' , :as => 'ban'
  delete 'user/:id' => 'admin#user_del' ,:as => 'destroy_user'
  get 'admin/user/edit/:id' => 'admin#user_edit' ,:as => 'edit_user'
  patch 'admin/user/update/:id' => 'admin#user_update' , :as => 'user'
  get 'admin/room/pending' => 'admin#rooms' ,:as => 'admin_rooms'

  get 'admin/room/approve/:id' => 'admin#approve_room' , :as => 'approve'
  get 'admin/room/reject/:id' => 'admin#reject_room' , :as => 'reject'
  get 'admin/room' => 'admin#room_entries' ,:as => 'admin_room_entries'
  get 'admin/reports' => 'admin#reports'
  get 'admin/reports/pre_approval' => 'admin#preapproval'
  get 'admin/reports/better_version' => 'admin#better_version'
  get 'admin/reports/spam' => 'admin#spam'

  get 'room/search' => 'search#search_by_name'
  post 'room/search_all' => 'search#search'
  get 'admin/search/user' => 'search#user'
  get 'room/voteup/:id' => 'versions#voteup' ,:as => 'voteup'
  get 'admin/search/entries' => 'search#entries'
  get 'admin/search/submission' => 'search#submission'

  get 'contact' => 'contact#contact'
  get 'privacy_policy' => 'contact#privacy_policy'
  get 'terms_conditions' => 'contact#terms_cond'
  post 'message' => 'contact#message'

end

app/views/admin/_report_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>TITLE/BUILDING NAME</th>
      <th>SUBMITTED BY</th>
      <th>DATE</th>
      <th>STATUS</th>
      <th>VERSION</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.version.name %></td>
        <td><%= report.version.room.user.username %></td>
        <td><%= report.version.created_at.to_date %></td>
        <td><%= report.version.status %></td>
        <td><%= report.version.typ %></td>
        <td><%= link_to 'EDIT' , edit_version_path(report.version) , method: :GET %></td>
        <td><%= link_to 'DELETE' , version_path(report.version) , method: :DELETE , data: { confirm: 'Are you sure?' }%></td>
        <td><%= link_to 'VIEW' , version_path(report.version) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @reports%>

app/views/admin/_table.html.erb
<div class="row">
  <div class="col-md-3">
    <%= form_tag(admin_search_entries_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "apply", "<option value=1 >Move to trash</option><option value=2 >Delete</option>".html_safe ,class: "form-control" %>
      <%= submit_tag 'Apply' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_entries_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "room", "<option value=1 >All Dates</option><option value=2 >Status/Approved</option><option value=3 >Status/Pending</option><option value=4 >Version</option>".html_safe ,class: "form-control"%>
      <%= submit_tag 'Filter' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_entries_path , :method => :get , :style => 'display: flex;') do %>
      <%= search_field('', :name , class: "form-control") %>
      <%= submit_tag 'Search' %>
    <% end %>
  </div>  
</div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>TITLE/BUILDING NAME</th>
      <th>SUBMITTED BY</th>
      <th>DATE</th>
      <th>STATUS</th>
      <th>VERSION</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @versions.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.room.user.username %></td>
        <td><%= room.created_at.to_date %></td>
        <td><%= room.status %></td>
        <td><%= room.typ %></td>
        <td><%= link_to 'EDIT' , edit_version_path(room) , method: :GET %></td>
        <td><%= link_to 'DELETE' , version_path(room) , method: :DELETE , data: { confirm: 'Are you sure?' }%></td>
        <td><%= link_to 'VIEW' , version_path(room) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @versions %>

app/views/admin/admin_signin.html.erb
<h2>Log In</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

app/views/admin/better_version.html.erb
<h4>ENTRY WITH CONFIRMED BETTER VERSION</h4>
<%= render 'table' %>

app/views/admin/preapproval.html.erb
<h4>PRE-APPROVAL</h4>
<%= render file: "admin/rooms" %>

app/views/admin/reports.html.erb
<h4>PRE-APPROVAL</h4>
<%= render file: "admin/rooms" %>
<br>
<h4>ENTRY WITH CONFIRMED BETTER VERSION</h4>
<%= render 'table' %>
<br>
<h4>SPAM/STATUS REPORTS</h4>
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#menu">NO LONGER EXIST</a></li>
  <li><a data-toggle="tab" href="#menu1">UNDER RENOVATION</a></li>
  <li><a data-toggle="tab" href="#menu2">INAPPROPRIATE CONTENT</a></li>
  <li><a data-toggle="tab" href="#menu3">SPAM</a></li>
</ul>

<div class="tab-content">
  <div id="menu" class="tab-pane fade in active">
	<% @reports = Report.no_longer_exist.paginate(:page => params[:page], :per_page => 2) %>
	<%= render 'report_table' %>
  </div>
  <div id="menu1" class="tab-pane fade">
    <% @reports = Report.under_renovation.paginate(:page => params[:page], :per_page => 2) %>
	<%= render 'report_table' %>
  </div>
  <div id="menu2" class="tab-pane fade">
    <% @reports = Report.inappropriate_content.paginate(:page => params[:page], :per_page => 2) %>
	<%= render 'report_table' %>
  </div>
  <div id="menu3" class="tab-pane fade">
  </div>
</div>

app/views/admin/room_entries.html.erb
<div class="row">
  <div class="col-md-3">
    <%= form_tag(admin_search_entries_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "apply", "<option value=1 >Move to trash</option><option value=2 >Delete</option>".html_safe ,class: "form-control" %>
      <%= submit_tag 'Apply' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_entries_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "room", "<option value=1 >All Dates</option><option value=2 >Status/Published</option><option value=3 >Status/Hidden</option><option value=4 >Version</option>".html_safe ,class: "form-control"%>
      <%= submit_tag 'Filter' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_entries_path , :method => :get , :style => 'display: flex;') do %>
      <%= search_field('', :name , class: "form-control") %>
      <%= submit_tag 'Search' %>
    <% end %>
  </div>  
</div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>TITLE/BUILDING NAME</th>
      <th>SUBMITTED BY</th>
      <th>DATE</th>
      <th>STATUS</th>
      <th>VERSION</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @version.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.room.user.username %></td>
        <td><%= room.created_at.to_date %></td>
        <td><%= room.status=='approved' ? 'published' : 'hidden' %></td>
        <td><%= room.typ=='newly' ? 'New' : 'Updated' %></td>
        <td><%= link_to 'EDIT' , edit_version_path(room) , method: :GET %></td>
        <td><%= link_to 'DELETE' , version_path(room) , method: :DELETE , data: { confirm: 'Are you sure?' }%></td>
        <td><%= link_to 'HIDE' , reject_path(room) %></td>
        <td><%= link_to 'VIEW' , version_path(room) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @version%>

app/views/admin/rooms.html.erb
<div class="row">
  <div class="col-md-3">
    <%= form_tag(admin_search_submission_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "apply", "<option value=1 >Move to trash</option><option value=2 >Delete</option>".html_safe ,class: "form-control" %>
      <%= submit_tag 'Apply' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_submission_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "room", "<option value=1 >All Dates</option><option value=2 >Status</option><option value=3 >Version</option>".html_safe ,class: "form-control"%>
      <%= submit_tag 'Filter' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_submission_path , :method => :get , :style => 'display: flex;') do %>
      <%= search_field('', :name , class: "form-control") %>
      <%= submit_tag 'Search' %>
    <% end %>
  </div>  
</div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>TITLE/BUILDING NAME</th>
      <th>SUBMITTED BY</th>
      <th>DATE</th>
      <th>STATUS</th>
      <th>VERSION</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @version.each do |version| %>
      <tr>
        <td><%= version.name %></td>
        <td><%= version.room.user.username %></td>
        <td><%= version.created_at.to_date %></td>
        <td><%= version.status %></td>
        <td><%= version.typ=='newly' ? 'New' : 'Updated' %></td>
        <td><%= link_to 'APPROVE' , approve_path(version)%></td>
        <td><%= link_to 'REJECT' , reject_path(version) %></td>
        <td><%= link_to 'VIEW' , version_path(version) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @version %>

app/views/admin/spam.html.erb
<h4>SPAM/STATUS REPORTS</h4>
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#menu">NO LONGER EXIST</a></li>
  <li><a data-toggle="tab" href="#menu1">UNDER RENOVATION</a></li>
  <li><a data-toggle="tab" href="#menu2">INAPPROPRIATE CONTENT</a></li>
  <li><a data-toggle="tab" href="#menu3">SPAM</a></li>
</ul>

<div class="tab-content">
  <div id="menu" class="tab-pane fade in active">
	<% @reports = Report.no_longer_exist.paginate(:page => params[:page], :per_page => 9) %>
	<%= render 'report_table' %>
  </div>
  <div id="menu1" class="tab-pane fade">
    <% @reports = Report.under_renovation.paginate(:page => params[:page], :per_page => 9) %>
	<%= render 'report_table' %>
  </div>
  <div id="menu2" class="tab-pane fade">
    <% @reports = Report.inappropriate_content.paginate(:page => params[:page], :per_page => 9) %>
	<%= render 'report_table' %>
  </div>
  <div id="menu3" class="tab-pane fade">
  </div>
</div>

app/views/admin/user.html.erb
<div class="row">
  <div class="col-md-3">
    <%= form_tag(admin_search_user_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "apply", "<option value=1 >Move to trash</option><option value=2 >Delete</option>".html_safe ,class: "form-control" %>
      <%= submit_tag 'Apply' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_user_path , :method => :get , :style => 'display: flex;') do %>
      <%= select_tag "user", "<option value=1 >Role/User</option><option value=2 >Role/Admin</option><option value=3 >Status/Active</option><option value=4 >Status/Suspended</option>".html_safe ,class: "form-control"%>
      <%= submit_tag 'Filter' %>
    <% end %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= form_tag(admin_search_user_path , :method => :get , :style => 'display: flex;') do %>
      <%= search_field('', :name , class: "form-control") %>
      <%= submit_tag 'Search' %>
    <% end %>
  </div>  
</div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>USERNAME</th>
      <th>ROLE</th>
      <th>DATE CREATED</th>
      <th>STATUS</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.role=='admin' ? 'Admin' : 'User' %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.status %></td>
        <td><%= link_to 'EDIT' , edit_user_path(user) %></td>
        <td><%= link_to 'DELETE' ,destroy_user_path(user), method: :delete , data: { confirm: 'Are you sure?' }%></td>
        <td><%= link_to 'BAN' , ban_path+'/'+user.id.to_s , data: { confirm: 'Are you sure?' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @user %>

app/views/admin/user_edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label(:username , "User Name") %>
  <%= f.text_field(:username) %>
  <br>
  <%= f.label(:role , "Role") %>
  <%= f.text_field(:role) %>
  <br>
  <%= f.label(:status , "Status") %>
  <%= f.text_field(:status) %>
  <br>
  <%= f.label(:ban , "Banned") %>
  <%= f.radio_button(:ban, true) %>
  <%= f.label(:ban_true, "Yes") %>
  <%= f.radio_button(:ban, false) %>
  <%= f.label(:ban_false, "No") %>
  <br>
  <%= f.submit %>
<% end %>