config/routes.rb
Rails.application.routes.draw do
  resources :versions
  resources :versions
  root 'versions#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'admin/signin' => 'admin#admin_signin'
  resources :photos
  resources :rooms
  get 'rooms/report/:id' => 'versions#report' , :as => 'report'
  post 'report/:id' => 'versions#creport' , :as => 'report_create'
  get 'admin/users' => 'admin#user' , :as => 'users'
  get 'admin/user/ban/:id' => 'admin#user_ban'
  get 'admin/user/ban' , :as => 'ban'
  delete 'user/:id' => 'admin#user_del' ,:as => 'destroy_user'
  get 'admin/user/edit/:id' => 'admin#user_edit' ,:as => 'edit_user'
  patch 'admin/user/update/:id' => 'admin#user_update' , :as => 'user'
  get 'admin/room/pending' => 'admin#rooms' ,:as => 'admin_rooms'

  get 'admin/room/approve/:id' => 'admin#approve_room' , :as => 'approve'
  get 'admin/room/reject/:id' => 'admin#reject_room' , :as => 'reject'
  get 'admin/room' => 'admin#room_entries' ,:as => 'admin_room_entries'
  get 'admin/reports' => 'admin#reports'
  get 'admin/reports/pre_approval' => 'admin#preapproval'
  get 'admin/reports/better_version' => 'admin#better_version'
  get 'admin/reports/spam' => 'admin#spam'

  get 'room/search' => 'search#search_by_name'
  post 'room/search_all' => 'search#search'
  get 'admin/search/user' => 'search#user'
  get 'room/voteup/:id' => 'versions#voteup' ,:as => 'voteup'
  get 'admin/search/entries' => 'search#entries'
  get 'admin/search/submission' => 'search#submission'

  get 'contact' => 'contact#contact'
  get 'privacy_policy' => 'contact#privacy_policy'
  get 'terms_conditions' => 'contact#terms_cond'
  post 'message' => 'contact#message'

end

app/models/version.rb
class Version < ActiveRecord::Base
	enum status: [ :pending , :approved , :rejected]
	enum typ: [:newly , :edited]
	has_many :photos , dependent: :destroy
	accepts_nested_attributes_for :photos
	has_many :reports , dependent: :destroy
	has_many :voteups , dependent: :destroy
	belongs_to :room

	scope :pending , lambda {where(:status => 0)}
	scope :approve_reject , lambda {where.not(:status => 0)}
	scope :approve , lambda {where(:status => 1)}
	scope :better , lambda{where.not(typ: 'newly')}
	scope :orignal , lambda{where(typ: 'newly')}
	scope :decending , lambda{ order(created_at: :desc)}

	attr_accessor :name_d

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy ,:creport , :voteup]
  before_action :authenticate_user!, except: [:index , :show]

  # GET /versions
  # GET /versions.json
  def index
    if user_signed_in?
      redirect_to admin_room_entries_path if current_user.role == 'admin'
    end
    
    @versions = Version.approved.orignal.paginate(:page => params[:page], :per_page => 4)

    p params
    @scrol = 'no'
    if params[:name].present? || params[:city].present? || params[:country].present?
      @scrol = 'yes'
      @versions = @versions.where(name: params[:name]) if params[:name]!=""
      @versions = @versions.where(city: params[:city]) if params[:city]!=""
      @versions = @versions.where(country: params[:country]) if params[:country]!=""
    end
    p @scrol
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @room = Room.create(user_id: current_user.id)
    @version = Version.new(version_params)
    @version.typ  = 0
    respond_to do |format|
      if params[:photo].present?
        if @version.save
          @version.update(room_id: @room.id)
          if params[:photo]['image']['0'].present?
            @photo = @version.photos.create!(:image => params[:photo]['image']['0'], :version_id => @version.id)
            if params[:photo]['image']['1'].present?
              @photo = @version.photos.create!(:image => params[:photo]['image']['1'], :version_id => @version.id)
              if params[:photo]['image']['2'].present?
                @photo = @version.photos.create!(:image => params[:photo]['image']['2'], :version_id => @version.id)
                if params[:photo]['image']['3'].present?
                  @photo = @version.photos.create!(:image => params[:photo]['image']['3'], :version_id => @version.id)
                end
              end
            end
          end
          format.html { redirect_to @version, notice: 'Version was successfully created.' }
          format.json { render :show, status: :created, location: @version }
        else
          format.html { render :new }
          format.json { render json: @version.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new, notice: 'Photos cant be empty.'}
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    if current_user.role == 'admin'
      @version.update(version_params)
      redirect_to admin_room_entries_path, notice: 'Version was successfully updated.'
    else
      if @version.room.versions.count == 1
        version = Version.new(version_params)
        version.room_id = @version.room.id
        version.typ  = 1
        respond_to do |format|
          if version.save
            if params[:photo].present?
              if params[:photo]['image']['0'].present?
                photo = version.photos.create!(:image => params[:photo]['image']['0'], :version_id => version.id)
                if params[:photo]['image']['1'].present?
                  photo = version.photos.create!(:image => params[:photo]['image']['1'], :version_id => version.id)
                  if params[:photo]['image']['2'].present?
                    photo = version.photos.create!(:image => params[:photo]['image']['2'], :version_id => version.id)
                    if params[:photo]['image']['3'].present?
                      photo = version.photos.create!(:image => params[:photo]['image']['3'], :version_id => version.id)
                    end
                  end
                end
              else
                @version.photos.each do |a|
                  p "Maza A Gya"
                  photo = a.dup
                  photo.save
                  photo.update(version_id: version.id)
                end
              end
            else
              @version.photos.each do |a|
                p "Photo attribute not present"
                photo = a.dup
                photo.save
                photo.update(version_id: version.id)
              end
            end
            format.html { redirect_to version_path, notice: 'Version was successfully updated.' }
            format.json { render :show, status: :ok, location: version }
          else
            format.html { render :edit }
            format.json { render json: version.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to root_path, notice: 'Updated version of room is already present.'
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def report

  end

  def creport
    if @version.reports.find_by_reporter_id(current_user.id).nil?
      report = Report.new()
      report.status = params[:status].to_i
      report.version_id = @version.id
      report.reporter_id = current_user.id
      respond_to do |format|
        if report.save
          format.html { redirect_to versions_path, notice: 'Report was successfully generated.' }
          format.json { render :show, status: :ok, location: @version }
        else
          format.html { render :index }
          format.json { render json: @version.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
          format.html { redirect_to versions_path, notice: 'Report was already generated.' }
          format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  def voteup
    if Voteup.where(:version_id => @version.id , :user_id => current_user.id).count>0
      redirect_to :back ,  notice: 'Already Voted.' 
    else
      vote = Voteup.create(version_id: @version.id , user_id: current_user.id)
      redirect_to :back , notice: 'Voted.'
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:name, :street, :floor, :city, :country, :description, :direction, :link , photos_attributes: [:image])
    end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<!-- <%= form_for(@version) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :direction %><br>
    <%= f.text_area :direction %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <%= f.fields_for :photo do |p| %>
   <div class="field">
     <%= p.file_field :photo_attributes, :id => "uploadBtn" , :class => "upload" ,:multiple => true, name: "photo[image][]" %>
   </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->




      <div class="r-content clearfix">
      <div class="container r-container">
          <h3>Fill up to add your entry</h3>
          <div class="row">
            <%= form_for(@version)  do |f| %>
            <% if @version.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

                <ul>
                <% @version.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="col-md-6 col-sm-6 col-xs-12">
                  <div class="form-border">
                          <div class="row border">
                              <div class="col-md-12">
                                  <%= f.label :name  , "Building Name"%>
                                  <%= f.text_field :name , class: "form-control-r"%>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-5">
                                  <%= f.label :street , "Street"%>
                                  <%= f.text_field :street , class: "form-control-r"%>
                                </div>
                                <div class="col-md-2">
                                  <%= f.label :floor , "Floor No"%>
                                  <%= f.text_field :floor , class: "form-control-r" %>
                                </div>
                                <div class="col-md-5">
                                  <%= f.label :name_d  , "Building Name"%>
                                  <%= f.text_field :name_d , class: "form-control-r"%>
                                </div>
                            </div>
                            <div class="row border">
                              <div class="col-md-4">
                                  <%= f.label :city , "City"%>
                                  <%= f.text_field :city , class: "form-control-r"%>
                                </div>
                                <div class="col-md-4">
                                  <%= f.label :country , "Country"%>
                                  <%= f.text_field :country , class: "form-control-r"%>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                  <%= f.label :description , "Description" %>
                                  <%= f.text_area :description , class: "form-control-comment" , rows: "5" %>
                                </div>
                            </div>
                    </div>
              </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                  <div class="form-border">
                          <div class="row">
                                <div class="col-md-12">
                                    <%= f.label :direction , "DIRECTIONS/ HOW TO GET HERE" %>
                                    <%= f.text_area :direction , class: "form-control-dir" , rows: "5" %>
                                </div>
                            </div>
                            <div class="row border">
                              <div class="col-md-9">
                                  <%= f.label :link , "YouTube Link"%>
                                  <%= f.text_field :link , class: "form-control-r"%>
                                </div>
                                <div class="col-md-3">
                                  <a class="youtube" href="#">FETCH</a>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                <label for="usr">Upload Photo</label>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                    <span class="file-wrapper">
                                        
                                        <%= f.file_field :photo_attributes, :id => "uploadBtn" , :class => "upload" , name: "photo[image][0]" %>
                                        <% if  @version.photos.first.present? %>
                                          <%= image_tag(@version.photos.first.image_url , class: "show_image_page") %>
                                        <% else %>
                                          <span class="button">Choose a Photo</span>
                                        <% end %>

                                  </span>
                                    <span class="file-wrapper">
                                      <%= f.file_field :photo_attributes, :id => "uploadBtn" , :class => "upload" , name: "photo[image][1]" %>
                                      <% if  @version.photos.second.present? %>
                                        <%= image_tag(@version.photos.second.image_url , class: "show_image_page") %>
                                      <% else %>
                                        <span class="button">Choose a Photo</span>
                                      <% end %>
                                  </span>
                                    <span class="file-wrapper">
                                    <%= f.file_field :photo_attributes, :id => "uploadBtn" , :class => "upload" , name: "photo[image][2]" %>
                                    <% if  @version.photos.third.present? %>
                                      <%= image_tag(@version.photos.third.image_url , class: "show_image_page") %>
                                    <% else %>
                                      <span class="button">Choose a Photo</span>
                                    <% end %>
                                  </span>
                                    <span class="file-wrapper">
                                    <%= f.file_field :photo_attributes, :id => "uploadBtn" , :class => "upload" , name: "photo[image][3]" %>
                                    <% if  @version.photos.fourth.present? %>
                                      <%= image_tag(@version.photos.fourth.image_url , class: "show_image_page") %>
                                    <% else %>
                                      <span class="button">Choose a Photo</span>
                                    <% end %>
                                  </span>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                <label for="usr">Feature Photo</label>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-6"></div>
                                <div class="col-md-3">
                                  <%= f.submit 'SAVE' , :class => "youtube" %> 
                                </div>
                                <div class="col-md-3">
                                  <a class="youtube" href="<%= root_path %>">CANCEL</a>
                                </div>
                            </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>

app/views/versions/edit.html.erb
<%= render 'form' %>

app/views/versions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', versions_path %>

app/views/versions/report.html.erb
<h4>Prayer area no longer exist? Help us update this entry</h4>
<%= form_tag( action: "creport") do%>
  <%= radio_button_tag(:status, "0") %>
  <%= label_tag(:status_child, "Prayer room no longer exist") %><br>
  <%= radio_button_tag(:status, "1") %>
  <%= label_tag(:status_adult, "Prayer room under renovation") %><br>
  <%= radio_button_tag(:status, "2") %>
  <%= label_tag(:status_adult, "Inappropiate content") %><br>
  <%= submit_tag %>
<% end %>

app/views/versions/show.html.erb
<!--
<p>
  <strong>Name:</strong>
  <%= @version.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @version.street %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @version.floor %>
</p>

<p>
  <strong>City:</strong>
  <%= @version.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @version.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @version.description %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @version.direction %>
</p>

<p>
  <strong>Link:</strong>
  <%= @version.link %>
</p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', :back %>
<%= link_to 'Report', report_path %>

-->



<div class="r-content clearfix">
      <div class="container r-container">
          <div class="row">
              <div class="col-md-7">
                  <div class="parkway">
                    <h3><%= @version.name %> <span>(<%= @version.country %>)</span></h3>
                    </div>
                </div>
                <div class="col-md-5">
                  <div class="entry">
                    <a href="<%= edit_version_path %>" class="edit-entry">edit this entry</a>
                      <a href="<%= new_version_path %>" class="add-entry"><span class="glyphicon glyphicon-plus"></span>add entry</a>
                  </div>
                </div>
            </div>
            <div class="row">
              <div class="col-md-6 col-sm-6 col-sx-12">
                  <div class="form-border-box clearfix">
                    <div class="bookmark">
                      <a href="#">bookmark</a>
                    </div>
                      <h2><strong>Location Address:</strong><%= @version.street %> <%= @version.city %>, <%= @version.country %></h2>
                        <p><%= @version.name %>, level <%= @version.floor %> at <%= @version.name %> (<%= @version.direction %>)<br><%= @version.description %>
                        </p>
                        <span class="checkin">Check In<span class="dotes">: </span><span><%= @version.room.checkins.count %></span></span>
                        <span class="post">Date Posted<span class="dotes">:</span><span><%= @version.created_at.strftime("%d-%m-%Y") %></span></span> 
                        <span class="status">Status<span class="dotes">:</span><span><%= @version.reports.count<5 ? "Available" : "Unavailable"  %></span></span>
                        <div class="share-icon">
                          <strong>Share This</strong>
                          <a href="https://www.facebook.com/"><%= image_tag("facebook-icon.png", :alt => "FB") %></a> 
                        <a href="https://www.twitter.com/"><%= image_tag("twitter-icon.png", :alt => "TW") %></a> 
                        <a href="https://www.google.com/"><%= image_tag("google-icon.png", :alt => "GOO") %></a>
                        </div>
                        <div class="voteup">
                          <strong>vote up +1</strong>
                            <div class="voteup-main">
                              <a href="<%= voteup_path %>" class="photo"><%= image_tag("icon_07.png", :alt => "ICON") %></a>
                                <div class="detail">
                                <p>This entry has been edited and has an alternate
version (Check below), Help us improve our list!, if you
find this accurate and helpful then please
vote this up to replace the other one</p>
</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-sx-12">
                  <ul class="nav nav-tabs responsive hidden-xs hidden-sm" id="tabs-1">
                      <li class="active"><a data-toggle="tab" href="#map" onclick="reload();">map</a></li>
                      <li class=""><a data-toggle="tab" href="#direction">get here</a></li>
                      <li class=""><a data-toggle="tab" href="#video">video</a></li>
                      <li class=""><a data-toggle="tab" href="#report">report</a></li>
                  </ul>
                  <div class="form-border">
                    <div class="tab-content">
                      <div id="map" class="tab-pane fade in active">
                        <script src="http://maps.googleapis.com/maps/api/js"></script>
                        <!-- <script>
                        function initialize() {
                          var mapProp = {
                            center:new google.maps.LatLng(51.508742,-0.120850),
                            zoom:14,
                            mapTypeId:google.maps.MapTypeId.ROADMAP
                          };
                          var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
                        }
                        google.maps.event.addDomListener(window, 'load', initialize);
                        </script> -->
<script type="text/javascript"> 

   var address = '<%= @version.name%>, <%= @version.street%>, <%= @version.city%>, <%= @version.country%>';

   var map = new google.maps.Map(document.getElementById('map'), { 
       mapTypeId: google.maps.MapTypeId.ROADMAP,
       zoom: 14
   });

   var geocoder = new google.maps.Geocoder();

   geocoder.geocode({
      'address': address
   }, 
   function(results, status) {
      if(status == google.maps.GeocoderStatus.OK) {
         new google.maps.Marker({
            position: results[0].geometry.location,
            map: map
         });
         map.setCenter(results[0].geometry.location);
      }
   });

   </script> 
                        <div id="googleMap" style="width:inherit;height:230px;"></div>
                      </div>
                      <div id="direction" class="tab-pane fade">
                        <br>
                        <p><%= @version.direction %></p>
                      </div>
                      <div id="video" class="tab-pane fade">
                        <% if @version.link.present? %>
                          <% if @version.link.include? "watch?v=" %>
                            <% url =  @version.link.split('watch?v=', @version.link.length) %>
                            <% p source = "https://www.youtube.com/embed/"+url[1]+"?rel=0" %>
                          <% else %>
                            <% source =  "https://www.youtube.com/embed/" %>
                          <% end %>
                        <% else %>
                          <% source =  "https://www.youtube.com/embed/" %>
                        <% end %>
                        <iframe width="420px" height="227px" src="<%= source %>" allowfullscreen></iframe>
                      </div>
                      <div id="report" class="tab-pane fade">
                        <h4>Prayer area no longer exist? Help us update this entry</h4>
                        <%= form_tag( action: "creport") do%>
                          <%= radio_button_tag(:status, "0") %>
                          <%= label_tag(:status_child, "Prayer room no longer exist") %><br>
                          <%= radio_button_tag(:status, "1") %>
                          <%= label_tag(:status_adult, "Prayer room under renovation") %><br>
                          <%= radio_button_tag(:status, "2") %>
                          <%= label_tag(:status_adult, "Inappropiate content") %><br>
                          <%= submit_tag "Report" , :class => "youtube" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>

                
            </div>
        <div class="row">
            <div class="col-md-4">
                <div class="galary">
                    <% if @version.photos.first.present? %>
                      <img src="<%= @version.photos.first.image_url %>" width="334" height="253" >
                    <% else %>
                      <%= image_tag("img10.jpg", height: '253', width: '334' , :alt => "ICON") %>
                    <% end %>
                </div>
            </div>
          <div class="col-md-4">
              <div class="galary">
                  <% if @version.photos.second.present? %>
                    <img src="<%= @version.photos.second.image_url %>" width="334" height="253">
                  <% else %>
                    <%= image_tag("img11.jpg", height: '253', width: '334' , :alt => "ICON") %>
                  <% end %>
                </div>
            </div>
          <div class="col-md-4">
              <div class="galary">
                  <% if @version.photos.third.present? %>
                    <img src="<%= @version.photos.third.image_url %>" width="334" height="253">
                  <% else %>
                    <%= image_tag("img12.jpg", height: '253', width: '334' , :alt => "ICON") %>
                  <% end %>
                </div>
            </div>
      </div>
        </div>
        <div class="container">
        <div class="org-btn">
          <a class="<%= @version.room.versions.first.id==@version.id ? "active" : "" %>" href="<%= version_path(@version.room.versions.first) %>">original</a>
            <% if @version.room.versions.count > 1 %>
              <a class="<%= @version.room.versions.last.id==@version.id ? "active" : "" %>" href="<%= version_path(@version.room.versions.last) %>">edited</a>
            <% end %>
            </div>
      </div>
    </div>

<script>
function reload() {
    location.reload();
}
</script>