config/routes.rb
Rails.application.routes.draw do
  resources :versions
  resources :versions
  root 'versions#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'admin/signin' => 'admin#admin_signin'
  resources :photos
  resources :rooms
  get 'rooms/report/:id' => 'versions#report' , :as => 'report'
  post 'report/:id' => 'versions#creport' , :as => 'report_create'
  get 'admin/users' => 'admin#user' , :as => 'users'
  get 'admin/user/ban/:id' => 'admin#user_ban'
  get 'admin/user/ban' , :as => 'ban'
  delete 'user/:id' => 'admin#user_del' ,:as => 'destroy_user'
  get 'admin/user/edit/:id' => 'admin#user_edit' ,:as => 'edit_user'
  patch 'admin/user/update/:id' => 'admin#user_update' , :as => 'user'
  get 'admin/room/pending' => 'admin#rooms' ,:as => 'admin_rooms'

  get 'admin/room/approve/:id' => 'admin#approve_room' , :as => 'approve'
  get 'admin/room/reject/:id' => 'admin#reject_room' , :as => 'reject'
  get 'admin/room' => 'admin#room_entries' ,:as => 'admin_room_entries'
  get 'admin/reports' => 'admin#reports'
  get 'admin/reports/pre_approval' => 'admin#preapproval'
  get 'admin/reports/better_version' => 'admin#better_version'
  get 'admin/reports/spam' => 'admin#spam'

  get 'room/search' => 'search#search_by_name'
  post 'room/search_all' => 'search#search'
  get 'admin/search/user' => 'search#user'
  get 'room/voteup/:id' => 'versions#voteup' ,:as => 'voteup'
  get 'admin/search/entries' => 'search#entries'
  get 'admin/search/submission' => 'search#submission'

  get 'contact' => 'contact#contact'
  get 'privacy_policy' => 'contact#privacy_policy'
  get 'terms_conditions' => 'contact#terms_cond'
  post 'message' => 'contact#message'

end

app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to :user
	has_many :versions , dependent: :destroy
	has_many :checkins , dependent: :destroy

	scope :decending , lambda{ order(created_at: :desc)}
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.text_field :floor %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :direction %><br>
    <%= f.text_area :direction %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <%= f.fields_for :photo do |p| %>
   <div class="field">
     <%= p.file_field :photo_attributes, :id => "uploadBtn" , :class => "upload" ,:multiple => true, name: "photo[image][]" %>
   </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @room.street %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @room.floor %>
</p>

<p>
  <strong>City:</strong>
  <%= @room.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @room.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @room.direction %>
</p>

<p>
  <strong>Link:</strong>
  <%= @room.link %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', :back %>
<%= link_to 'Report', report_path %>