config/routes.rb
Rails.application.routes.draw do
  resources :versions
  resources :versions
  root 'versions#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'admin/signin' => 'admin#admin_signin'
  resources :photos
  resources :rooms
  get 'rooms/report/:id' => 'versions#report' , :as => 'report'
  post 'report/:id' => 'versions#creport' , :as => 'report_create'
  get 'admin/users' => 'admin#user' , :as => 'users'
  get 'admin/user/ban/:id' => 'admin#user_ban'
  get 'admin/user/ban' , :as => 'ban'
  delete 'user/:id' => 'admin#user_del' ,:as => 'destroy_user'
  get 'admin/user/edit/:id' => 'admin#user_edit' ,:as => 'edit_user'
  patch 'admin/user/update/:id' => 'admin#user_update' , :as => 'user'
  get 'admin/room/pending' => 'admin#rooms' ,:as => 'admin_rooms'

  get 'admin/room/approve/:id' => 'admin#approve_room' , :as => 'approve'
  get 'admin/room/reject/:id' => 'admin#reject_room' , :as => 'reject'
  get 'admin/room' => 'admin#room_entries' ,:as => 'admin_room_entries'
  get 'admin/reports' => 'admin#reports'
  get 'admin/reports/pre_approval' => 'admin#preapproval'
  get 'admin/reports/better_version' => 'admin#better_version'
  get 'admin/reports/spam' => 'admin#spam'

  get 'room/search' => 'search#search_by_name'
  post 'room/search_all' => 'search#search'
  get 'admin/search/user' => 'search#user'
  get 'room/voteup/:id' => 'versions#voteup' ,:as => 'voteup'
  get 'admin/search/entries' => 'search#entries'
  get 'admin/search/submission' => 'search#submission'

  get 'contact' => 'contact#contact'
  get 'privacy_policy' => 'contact#privacy_policy'
  get 'terms_conditions' => 'contact#terms_cond'
  post 'message' => 'contact#message'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrayWhere</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row text_center_adjust">
			<h3 style="float: left;">PrayWhere</h3>
			<h3 style="float: right;">Hello, admin! </h3>
			<% if user_signed_in? %>
				<h5 style="float: right; margin-right: 20px;margin-top: 25px;"><%= link_to "SignOut" , destroy_user_session_path , method: :delete%></h5>
		    <% end %>
		</div>
	</div>
	<div class="container-fluid" style="border-top: 5px solid #00ADFF;">
		<div class="row" style="margin-top: 1%;">
			<div class="col-md-2 dash">
				<ul class="nav nav-pills nav-stacked" >
				    <li><h4>DASHBOARD</h4></li>
				    <li class="<%= current_page?(controller: 'admin' , action: 'room_entries')? 'active' : ' ' %>"><%= link_to ' ENTRIES' , admin_room_entries_path ,:class =>"glyphicon glyphicon-file" %></li>
				    <li class="<%= current_page?(controller: 'admin' , action: 'user')? 'active' : ' ' %>"><%= link_to ' USERS' , users_path ,:class =>"glyphicon glyphicon-user"%></li>
				    <li><a href="#" class="glyphicon glyphicon-cog"> TOOLS</a></li>
				    <li class=" <%= current_page?(controller: 'admin' , action: 'rooms')? 'active' : ' ' %>"><%= link_to ' SUBMISSIONS', admin_rooms_path , :class =>"glyphicon glyphicon-list-alt" %>
				    </li>
				    <li class="<%= current_page?(controller: 'admin' , action: 'reports')? 'active' : ' ' %>"><%= link_to ' REPORTS' , admin_reports_path ,:class =>"glyphicon glyphicon-file" %>
				    	<ul>
				    		<li><%= link_to ' PRE-APPROVAL' , admin_reports_pre_approval_path %></li>
				    		<li><%= link_to ' BETTER VERSION' , admin_reports_better_version_path %></li>
				    		<li><%= link_to ' SPAM/STATUS' , admin_reports_spam_path %></li>
				    	</ul>
				    </li>
				    <li><a href="#" class="glyphicon glyphicon-stats"> ANALYTICS</a></li>
				</ul>
			</div>
			<div class="col-md-10 admin_yield">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>PrayWhere</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
    
</head>

<body>
  <div id="wrapper">
    <div class="header-nav">
      <div class="container">
        <div class="row">
          <div class="col-md-7 col-sm-12 col-xs-12">
          	<div class="logo"> 
            	<a href="#"><%= image_tag("logo.png", :alt => "Logo" , width: '152' , height: 'auto') %></a> 
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                 </button>
             </div>
            <div class="prayer">
            	<strong>"Prayer Is One Of The Foundation Of Being A Muslim"</strong>
            </div>
          </div>
          <div class="col-md-3 col-sm-12 col-xs-12">
          	<div class="navigation">
                <div class="navbar" role="navigation">
                  <div class="navbar-collapse collapse">
                      <ul class="nav-menu nav clearfix">
                        <li class="<%= request.original_fullpath=='/'? 'active' : ' ' %>"><%= link_to 'Home', root_path %></li>
                        <li class="<%= request.original_fullpath=='/contact'? 'active' : ' ' %>" style="margin-right: -5px;"><%= link_to 'About', contact_path  %></li>
                        <li class="<%= request.original_fullpath=='/contact'? 'active' : ' ' %>"><%= link_to 'Contact us', contact_path %></li>
                     </ul>
                  </div>
                </div>
            </div>
          </div>
          <div class="col-md-2 col-sm-12 hidden-sm col-xs-12 hidden-xs">
            <div class="login"> 
            	<% if user_signed_in? %>
      					<%= current_user.username %>
      					<%= link_to 'SignOut', destroy_user_session_path , method: :delete%>
				      <% else %> 
	            	 <a class="active" data-toggle="modal" data-target="#myModal-second">Register</a> 
	            	<a class="active" data-toggle="modal" data-target="#myModal">Login </a>
            	<% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <% if name.to_s == 'notice' %>
      <script type="text/javascript">alertify.success('<%= msg%>');</script>
      <%else%>
     <script type="text/javascript">alertify.error('<%= msg%>');</script>
    <%end%>
  <% end %>
<% end %>



    <%= yield %>

    
    <footer class="footer">
    <div class="container">
      
      <div class="row">
        <div class="col-md-2 col-sm-4 col-xs-4">
          <span>get in touch</span>
          <div class="social-icon"> 
          	<a href="https://www.facebook.com/MusimPrayerAreaSingapore"><%= image_tag("icon05_03.png", :alt => "FB") %></a> 
            <a href="https://www.twitter.com/"><%= image_tag("icon04_03.png", :alt => "TW") %></a> 
            <a href="https://www.google.com/"><%= image_tag("icon03_03.png", :alt => "GOO") %></a> 
          </div>
          <span class="footer_links_pray"><%= link_to 'Contact us', contact_path %></span> 
          <span class="footer_links_pray"><%= link_to 'Terms and Condition', terms_conditions_path %></span> 
          <span class="footer_links_pray"><%= link_to 'Privacy Policy', privacy_policy_path %></span>
          <span>faq</span>
          <span class="footer_links_pray"><%= link_to 'About us', contact_path %></span> 
        </div>
        <div class="col-md-5 col-sm-8 col-xs-8">
          <div class="list-group-item">
            <span>recent post</span>
            <% if Room.last.present? %>
	            <% if Room.last.versions.first.present? %>
	            	<% @roomL = Room.last.versions.first %>
		            <div class="photo"> 
		            	<img src="<%= @roomL.photos.first.image_url %>" width="91" height="79" alt="image descraption"> 
		            </div>
		            <div class="item-list">
		              <h3><%= @roomL.name %></h3>
		              <p>Location Address: <%= @roomL.street%>, Level <%= @roomL.floor%></p>
		            </div>
	            <% end %>
	        <% end %>
          </div>
          <div class="list-group-item">
          <% if Room.decending.third.present? %>
          	<% if Room.decending.third.versions.first.present? %>
            	<% @roomL = Room.decending.third.versions.first %>
	            <div class="photo"> 
	            	<img src="<%= @roomL.photos.first.image_url %>" width="91" height="79" alt="image descraption"> 
	            </div>
	            <div class="item-list">
	              <h3><%= @roomL.name %></h3>
	              <p>Location Address: <%= @roomL.street%>, Level <%= @roomL.floor%></p>
	            </div>
	        <% end %>
	      <% end %>
          </div>
        </div>
        <div class="col-md-5 col-sm-8 hidden-sm col-xs-6 hidden-xs">
          <div class="list-group-item">
          <% if Room.decending.second.present? %>
          	<% if Room.decending.second.versions.first.present? %>
            	<% @roomL = Room.decending.second.versions.first %>
	            <div class="photo"> 
	            	<img src="<%= @roomL.photos.first.image_url %>" width="91" height="79" alt="image descraption">
	            </div>
	            <div class="item-list">
	              <h3><%= @roomL.name %></h3>
	              <p>Location Address: <%= @roomL.street%>, Level <%= @roomL.floor%></p>
	            </div>
	        <% end %>
	      <% end %>
          </div>
          <div class="list-group-item">
          <% if Room.decending.fourth.present? %>
          	<% if Room.decending.fourth.versions.first.present? %>
            	<% @roomL = Room.decending.fourth.versions.first %>
	            <div class="photo"> 
	            	<img src="<%= @roomL.photos.first.image_url %>" width="91" height="79" alt="image descraption"> 
	            </div>
	            <div class="item-list">
	              <h3><%= @roomL.name %></h3>
	              <p>Location Address: <%= @roomL.street%>, Level <%= @roomL.floor%></p>
	            </div>
	        <% end %>
	      <% end %>
          </div>
        </div>
      </div>
      </footer>
      
      
      <!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <div class="form-row clearfix">
        	<a href="<%= user_google_oauth2_omniauth_authorize_path %>"><%= image_tag("google.jpg", :alt => "Google") %></a>
        </div>
        <div class="form-row clearfix">
        	<a href="<%= user_facebook_omniauth_authorize_path %>"><%= image_tag("facebook.jpg", :alt => "Facebook") %></a>
        </div>
        <div class="form-row or-line">
        	<span class="title">or</span>
        </div>

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-row clearfix">
        <%= f.email_field :email, autofocus: true , class: "form-control" , placeholder: "Email Address" %>
      </div>

      <div class="form-row clearfix">
        <%= f.password_field :password, autocomplete: "off" , class: "form-control" , placeholder: "Password" %>
      </div>

      <div class="form-row clearfix actions">
        <%= f.submit "Log in" , class: "form-login" %>
      </div>
    <% end %>



        <div class="form-row clearfix">
          <p><a data-dismiss="modal" data-toggle="modal" href="#forgot" class="forget-password">Forgot your password?</a></p>
          <p>Don't have an account? <a data-dismiss="modal" data-toggle="modal" href="#myModal-second" class="sign-up"> Sign up</a></p>

        </div>
    </div>

  </div>
</div>
</div>


<!-- Modal second -->
  <div id="myModal-second" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="form-row clearfix">
                    <a href="<%= user_google_oauth2_omniauth_authorize_path %>"><%= image_tag("google.jpg", :alt => "Google") %></a>
                </div>
                <div class="form-row clearfix">
                   <a href="<%= user_facebook_omniauth_authorize_path %>"><%= image_tag("facebook.jpg", :alt => "Facebook") %></a>
                </div>
                <div class="form-row or-line">
                    <span class="title">or</span>
                </div>
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= devise_error_messages! %>

                  <div class="form-row clearfix">
                      <%= f.email_field :email, autofocus: true , class: "form-control" , placeholder: "Email" %>
                  </div>
                  <div class="form-row clearfix">
                      <% if @minimum_password_length %>
                        <em>(<%= @minimum_password_length %> characters minimum)</em>
                      <% end %><br />
                      <%= f.password_field :password, autocomplete: "off" , class: "form-control" , placeholder: "Password"%>
                  </div>
                  <div class="form-row clearfix">
                      <%= f.password_field :password_confirmation, autocomplete: "off" , class: "form-control" , placeholder: "Confirm Password"%>
                  </div>
                  <div class="form-row clearfix">
                      <%= f.submit "Sign up" , class: "sign-up-first"%>
                  </div>
                  <div class="form-row clearfix">
                      <div class="checkbox">
                          <label><input type="checkbox" value=""><p>Remember My Password</p></label>
                      </div>
                  </div>
                <% end %>
              </div>
        </div>
    </div>
  </div>


  <!-- Modal forgot -->
  <div id="forgot" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="form-row clearfix">
                    <a href="<%= user_google_oauth2_omniauth_authorize_path %>"><%= image_tag("google.jpg", :alt => "Google") %></a>
                </div>
                <div class="form-row clearfix">
                   <a href="<%= user_facebook_omniauth_authorize_path %>"><%= image_tag("facebook.jpg", :alt => "Facebook") %></a>
                </div>
                <div class="form-row or-line">
                    <span class="title">or</span>
                </div>

                <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
                    <%= devise_error_messages! %>

                    <div class="form-row clearfix">
                      <%= f.email_field :email, autofocus: true , class: "form-control" , placeholder: "Email" %>
                    </div>

                    <div class="form-row clearfix">
                      <%= f.submit "Send me reset password instructions" , class: "sign-up-first"%>
                    </div>
                  <% end %>

                  <div class="form-row clearfix">
                    <p>Already have an account? <a data-dismiss="modal" data-toggle="modal" href="#myModal" class="sign-up"> Sign in</a></p>
                    <p>Don't have an account? <a data-dismiss="modal" data-toggle="modal" href="#myModal-second" class="sign-up"> Sign up</a></p>

                  </div>
              </div>
        </div>
    </div>
  </div>
</body>
</html>